[package]
name = "texture-cache-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "maketiled"
path = "src/maketiled.rs"

[lib]
crate-type = ["lib"]

[dependencies]

[dev-dependencies]
image = "0.25.9"
tempfile = "3.23.0"
